name: esd_mobil
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  aad_oauth: ^0.3.0
  animated_splash_screen: ^1.1.0
  auto_size_text: ^2.1.0
  build_runner: ^2.1.1
  cloud_firestore: ^2.5.4
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  fast_immutable_collections: ^7.0.3
  file_picker: ^4.1.1
  firebase_auth: ^3.1.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^6.1.0+1
  flutter_mobx: ^2.0.2
  flutter_multiselect: ^1.0.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  get: ^4.3.8
  http: ^0.13.3
  image_picker: any
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  kartal: ^2.1.0
  lottie: ^1.2.1
  mime: ^1.0.1
  mime_type: ^1.0.0
  mobx: ^2.0.4
  mobx_codegen: ^2.0.3
  multi_select_flutter: ^4.0.0
  numberpicker: ^2.1.1
  path: ^1.8.0
  path_provider: any
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  syncfusion_flutter_charts: ^19.3.48
  url_launcher: any
  vexana: ^2.3.0
  webview_flutter: ^2.0.4

dependency_overrides:
  analyzer: ^2.1.0
  meta: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/svg/
    - assets/image/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
