name: fluttermvvmtemplate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  build_runner: ^2.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_svg: ^0.22.0
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  mobx: ^2.0.4
  mobx_codegen: ^2.0.3
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  vexana: ^2.3.0

dependency_overrides:
  analyzer: ^2.1.0
  meta: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/svg/
    - assets/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
